### ISSUE TITLE
New Hydra Version Changes

### ISSUE THREAD

**Issue by YanjieZe** [qq456cvb/CanonicalVoting#1]
There needs some changes for the new version of Hydra.

In Hydra 0.11:
```
@hydra.main(config_path="conf/config.yaml")
```
In Hydria 1.0:
```
@hydra.main(config_path="conf", config_name="config")
```
Reference: https://hydra.cc/docs/next/upgrades/0.11_to_1.0/config_path_changes/

**Comment by qq456cvb** [comment]
Fixed in commit 3eebcc33328e9b4c7dfc298e354ef32c1a211ba1.
