### ISSUE TITLE
could you prove the verison of all depencies?

### ISSUE THREAD

**Issue by saladcat** [qq456cvb/CanonicalVoting#2]
I install the last verision of all denpendcies, but tons of error happended.

**Comment by qq456cvb** [comment]
Hi, thanks for your interest. We have updated our install dependencies to more recent versions, and it have been tested ok on our Ubuntu 16.04 server. Check whether you could install them and run the script following the updated guidelines.

**Comment by saladcat** [comment]
Thanks for you reply! that works for me
