### ISSUE TITLE
I download pretrain weight and run eval_joint.py but nan happend 

### ISSUE THREAD

**Issue by saladcat** [qq456cvb/CanonicalVoting#4]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/22851795/164480690-4994f523-223e-462d-a019-0df97adad862.png">

and then I try to train from scratch, the result seems good as following.
<img width="936" alt="image" src="https://user-images.githubusercontent.com/22851795/164480913-305c10a0-3387-43ff-ab6c-79df6429ed92.png">

but when i take the ckpt to run eval_joint.py, the same nan result happended
 
<img width="929" alt="image" src="https://user-images.githubusercontent.com/22851795/164481275-19612c85-5379-456b-983a-f70c81cb5ece.png">

**Comment by qq456cvb** [comment]
Hi, this problem is due to a bug in map evaluation. We have fixed that in 4fc2eed4c9463acaff9eccf524b22a4d127bcabb.
